DROP TABLE NEW_SURVEY;

CREATE TABLE NEW_SURVEY (
        SURVEY_ID BIGINT NOT NULL AUTO_INCREMENT,
        SURVEY_SEASON VARCHAR(255) NOT NULL,
        SURVEY_FRUIT VARCHAR(255) NOT NULL,
        PRIMARY KEY (SURVEY_ID)
);

SELECT * FROM NEW_SURVEY;
