DROP TABLE MEMBER;

CREATE TABLE MEMBER (
    ID LONG AUTO_INCREMENT NOT NULL,    -- 아이디 (기본키)
    NAME VARCHAR(255),                  -- 이름
    AGE INTEGER NOT NULL,               -- 나이
    PRIMARY KEY (ID)
);

INSERT INTO MEMBER(NAME, AGE) VALUES('sally', 30);
INSERT INTO MEMBER(NAME, AGE) VALUES('john', 20);
INSERT INTO MEMBER(NAME, AGE) VALUES('philip', 40);